version: '3.7'

######################################## HINTS ######################################################
# Structure
# A docker-compose file consists of services which are started with the command "docker-compose up".
# Currently there are 4 services defined: save-client, elasticsearch, kibana and mosquitto.

# Before starting the application images must be created: "docker-compose build"
# Its highly recommended to stop the application with "docker-compose down".
# Closing the terminal or CTRL + C (SIGINT) will only stop the containers.
#
# Use `docker-compose logs -f save-client` to follow only the logs of save-client container
# Use `docker-compose config` to see the interpreted docker-compose file.

#####################################################################################################
services:
  save-client:
    build: .
    image: save-client:1.0.0
    networks:
      - save_network
    ports: # like publish (docker cli) mapping for localhost-container
      - '3000:3000'
    expose: # ports visible only between containers on network
      - '1883'
      - '9200'
    depends_on:
      - mosquitto
  #    volumes:
  #      - type: bind
  #        source: ./src/dataschema
  #        target: /SAVE-Interface-Client/src/dataschema
  #      - type: bind
  #        source: ./config.js
  #        target: /SAVE-Interface-Client/config.js

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    expose:
      - '9200'
    networks:
      - save_network
    environment:
      - 'ES_JAVA_OPTS=-Xmx256m -Xms256m' #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.ingest=false
      - xpack.security.enabled=false
      - xpack.sql.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      #- bootstrap.memory_lock=true ??
      #- discovery.type=single-node ??

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    networks:
      - save_network
    ports:
      - '5601:5601'
    environment:
      - xpack.ml.enabled=false
      - xpack.reporting.enabled=false
      - xpack.searchprofiler.enabled=false
      - xpack.grokdebugger.enabled=false

  mosquitto:
    image: eclipse-mosquitto
    networks:
      - save_network
    ports:
      - '${SAVE_MOSQUITTO_PORT:-8883}:1883' # (8883 is exposed to outside)

networks:
  save_network:
