module.exports = [
  {
    ADDRESS: 'conveyorbelt/position1',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 45.806960425813394,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 46.06157910486104,
        },
        Bend: {
          name: 'Bend',
          unit: 'mm',
          description: 'Bend',
          value: -0.0035894022485348856,
        },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 45.542958972510874,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 46.06173043629285,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 22.660152498215574,
        },
      },
      usecase_id: '',
      timestamp: 9,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864056815,
  },
  {
    ADDRESS: 'conveyorbelt/position2',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 46.93005441161107,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 47.04501478839873,
        },
        Bend: { name: 'Bend', unit: 'mm', description: 'Bend', value: 0.02 },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 47.031939448521726,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 47.09758830566932,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 22.660152498215574,
        },
      },
      usecase_id: '',
      timestamp: 9,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864057424,
  },
  {
    ADDRESS: 'conveyorbelt/position3',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 47.085811481245884,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 47.049304201584704,
        },
        Bend: { name: 'Bend', unit: 'mm', description: 'Bend', value: 0.02 },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 46.92545207608588,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 47.06384111208769,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 22.660152498215574,
        },
      },
      usecase_id: '',
      timestamp: 9,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864057912,
  },
  {
    ADDRESS: 'conveyorbelt/position1',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 46.04477508853126,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 45.616274885826954,
        },
        Bend: {
          name: 'Bend',
          unit: 'mm',
          description: 'Bend',
          value: -7.112835563037165e-4,
        },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 46.3228715682784,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 46.026836695166125,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 23.451887058167472,
        },
      },
      usecase_id: '',
      timestamp: 8,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864049979,
  },
  {
    ADDRESS: 'conveyorbelt/position2',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 46.93005441161107,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 47.04501478839873,
        },
        Bend: { name: 'Bend', unit: 'mm', description: 'Bend', value: 0.02 },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 47.031939448521726,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 47.09758830566932,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 22.660152498215574,
        },
      },
      usecase_id: '',
      timestamp: 9,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864057424,
  },
  {
    ADDRESS: 'conveyorbelt/position3',
    AGENT: 'ConrodSimulator',
    VALUE: {
      name: 'Conrod',
      machine_state: 'RUNNING',
      featuremap: {
        GAuntenquer: {
          name: 'GAuntenquer',
          unit: 'mm',
          description: 'DM GA unten +45o',
          value: 46.92007425710866,
        },
        GAobenquer: {
          name: 'GAobenquer',
          unit: 'mm',
          description: 'DM GA oben +45o',
          value: 46.99041187598037,
        },
        Bend: { name: 'Bend', unit: 'mm', description: 'Bend', value: 0.02 },
        GAuntenlngs: {
          name: 'GAuntenlngs',
          unit: 'mm',
          description: 'DM GA unten -45o',
          value: 47.09709436396412,
        },
        GAobenlngs: {
          name: 'GAobenlngs',
          unit: 'mm',
          description: 'DM GA oben -45o',
          value: 46.99426570314777,
        },
        KAobenlngs: {
          name: 'KAobenlngs',
          unit: 'mm',
          description: 'DM KA oben 0o',
          value: 22.63605840900692,
        },
      },
      usecase_id: '',
      timestamp: 3,
      type: 'save.communication.messages.Product',
    },
    timeStamp: 1570864016330,
  },
];
