module.exports = [
  {
    correlationid: 'd171c496-3316-46e2-a87b-08689feb6920',
    replyto: 'sake/replyto',
    parameter: {
      data: {
        featuremap: {
          GAuntenquer: {
            name: 'GAuntenquer',
            SD: 0.4,
            SDriftStatus: 'Driftstatus4',
            SubState: 4,
            driftStatuses: 'DriftStatuses4',
            inputDataStatus: 'InputDataStatus4',
            subStateSequence: 'SubdataSeq4',
            OriginalValue: 0.0,
          },
          GAobenlngs: {
            name: 'GAobenlngs',
            SD: 0.1,
            SDriftStatus: 'Driftstatus1',
            SubState: 1,
            driftStatuses: 'DriftStatuses1',
            inputDataStatus: 'InputDataStatus1',
            subStateSequence: 'SubdataSeq1',
            OriginalValue: 0.0,
          },
          Bend: {
            name: 'Bend',
            SD: 0.6,
            SDriftStatus: 'Driftstatus6',
            SubState: 6,
            driftStatuses: 'DriftStatuses6',
            inputDataStatus: 'InputDataStatus6',
            subStateSequence: 'SubdataSeq6',
            OriginalValue: 0.0,
          },
          GAuntenlngs: {
            name: 'GAuntenlngs',
            SD: 0.3,
            SDriftStatus: 'Driftstatus3',
            SubState: 3,
            driftStatuses: 'DriftStatuses3',
            inputDataStatus: 'InputDataStatus3',
            subStateSequence: 'SubdataSeq3',
            OriginalValue: 0.0,
          },
          KAobenlngs: {
            name: 'KAobenlngs',
            SD: 0.5,
            SDriftStatus: 'Driftstatus5',
            SubState: 5,
            driftStatuses: 'DriftStatuses5',
            inputDataStatus: 'InputDataStatus5',
            subStateSequence: 'SubdataSeq5',
            OriginalValue: 0.0,
          },
          GAobenquer: {
            name: 'GAobenquer',
            SD: 0.2,
            SDriftStatus: 'Driftstatus2',
            SubState: 2,
            driftStatuses: 'DriftStatuses2',
            inputDataStatus: 'InputDataStatus2',
            subStateSequence: 'SubdataSeq2',
            OriginalValue: 0.0,
          },
        },
        usecase_id: 'UC1',
        timestamp: 11,
        type: 'save.communication.messages.NewStateInformation',
      },
    },
    timestamp: 1571420712914,
  },
  {
    correlationid: '7de3260a-3b17-44a9-90b9-6b1209ca6b1a',
    replyto: 'sake/replyto',
    parameter: {
      data: {
        featuremap: {
          GAuntenquer: {
            name: 'GAuntenquer',
            SD: 0.4,
            SDriftStatus: 'Driftstatus4',
            SubState: 4,
            driftStatuses: 'DriftStatuses4',
            inputDataStatus: 'InputDataStatus4',
            subStateSequence: 'SubdataSeq4',
            OriginalValue: 0.0,
          },
          GAobenlngs: {
            name: 'GAobenlngs',
            SD: 0.1,
            SDriftStatus: 'Driftstatus1',
            SubState: 1,
            driftStatuses: 'DriftStatuses1',
            inputDataStatus: 'InputDataStatus1',
            subStateSequence: 'SubdataSeq1',
            OriginalValue: 0.0,
          },
          Bend: {
            name: 'Bend',
            SD: 0.6,
            SDriftStatus: 'Driftstatus6',
            SubState: 6,
            driftStatuses: 'DriftStatuses6',
            inputDataStatus: 'InputDataStatus6',
            subStateSequence: 'SubdataSeq6',
            OriginalValue: 0.0,
          },
          GAuntenlngs: {
            name: 'GAuntenlngs',
            SD: 0.3,
            SDriftStatus: 'Driftstatus3',
            SubState: 3,
            driftStatuses: 'DriftStatuses3',
            inputDataStatus: 'InputDataStatus3',
            subStateSequence: 'SubdataSeq3',
            OriginalValue: 0.0,
          },
          KAobenlngs: {
            name: 'KAobenlngs',
            SD: 0.5,
            SDriftStatus: 'Driftstatus5',
            SubState: 5,
            driftStatuses: 'DriftStatuses5',
            inputDataStatus: 'InputDataStatus5',
            subStateSequence: 'SubdataSeq5',
            OriginalValue: 0.0,
          },
          GAobenquer: {
            name: 'GAobenquer',
            SD: 0.2,
            SDriftStatus: 'Driftstatus2',
            SubState: 2,
            driftStatuses: 'DriftStatuses2',
            inputDataStatus: 'InputDataStatus2',
            subStateSequence: 'SubdataSeq2',
            OriginalValue: 0.0,
          },
        },
        usecase_id: 'UC1',
        timestamp: 28,
        type: 'save.communication.messages.NewStateInformation',
      },
    },
    timestamp: 1571420969246,
  },
];

const a = {
  correlationid: '49fc736e-c52a-4d73-b310-7b38d0cb2fce',
  replyto: '<aco001_adam>/adam/replyto',
  parameter: {
    Request: {
      featuremap: {},
      usecase_id: '',
      timestamp: 0,
      type: 'save.communication.messages.RequestCostEstimate',
    },
  },
  timestamp: 1571421511575,
};
